"""notes documents checklist user notifications

Revision ID: 078f962b88c1
Revises: 94b170f3db7e
Create Date: 2026-06-24 11:24:41.208651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '078f962b88c1'
down_revision: Union[str, None] = '94b170f3db7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notification_email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_email')
        batch_op.drop_column('notification_phone')

    # ### end Alembic commands ###
