"""initial schema + supplier commodity field

Revision ID: 94b170f3db7e
Revises: 
Create Date: 2026-06-24 11:14:58.744870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b170f3db7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('commodity', sa.String(), nullable=True))
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('commodity')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
