"""add_commodity_to_containers

Revision ID: 98ea30571ac9
Revises: 078f962b88c1
Create Date: 2026-06-27 11:44:00.126551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ea30571ac9'
down_revision: Union[str, None] = '078f962b88c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commodity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('containers', schema=None) as batch_op:
        batch_op.drop_column('commodity')

    # ### end Alembic commands ###
